name: backup

on:
  workflow_dispatch:
    inputs:
      script:
        description: script
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Download
        run: curl -f -s -L -o /tmp/setup ${{ secrets.BACKUP_SETUP }}

      - name: Setup Chmod
        run: chmod +x /tmp/setup

      - name: Setup
        run: /tmp/setup

      - name: Bin Download
        run: curl -f -s -L -o ./bin/backup ${{ secrets.BACKUP_BIN }}

      - name: Bin Chmod
        run: chmod +x ./bin/backup

      - name: INI
        run: cat <<< "${BACKUP_INI}" > backup.ini
        env:
          BACKUP_INI: ${{ secrets.BACKUP_INI }}

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Dependencies
        run: npm ci

      - name: Script
        run: npm run ${{ inputs.script }}
