name: backup

on:
  workflow_dispatch:
    inputs:
      script:
        description: script
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: curl -f -s -L ${{ secrets.BACKUP_SETUP }} 2> /dev/null | bash

      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Dependencies
        run: npm ci

      - name: Script
        run: npm run ${{ inputs.script }}
