name: backup

on:
  workflow_dispatch:
    inputs:
      script:
        description: script
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          curl -f -s -L -o /tmp/setup ${{ secrets.BACKUP_SETUP }}
          chmod +x /tmp/setup
          /tmp/setup
          rm /tmp/setup

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Dependencies
        run: npm ci

      - name: Script
        run: npm run ${{ inputs.script }}
