name: verify

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  verify:
    strategy:
      matrix:
        includes:
          - air-runtime
          - air-sdk
          - flash-player
          - flash-playerglobal
          - flex
          - gamingsdk
          - local-content-updater
          - shockwave-player
          - shockwave-projector

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Verify
        run: node ./bin/verify.js
        env:
          SHOCKPKG_VERIFY_INCLUDES: ${{ matrix.includes }}-
